server:
  port: 9191

spring:
  application:
    name: springboot-all-provider
  dubbo:
    appname: springboot-duboo-provider
    registry: zookeeper://localhost:2181
  datasource:
      url: jdbc:mysql://localhost:3306/springboot?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: fuckallhacker
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    password: 123456
    host: localhost

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.du.springboot.entity